accounts/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/8/5 0005 上午 10:14
__Author__ = '村长'
from django.urls import path, re_path, include
from accounts import views
from accounts import permission

app_name = 'accounts'

urlpatterns = [

    re_path(r'^login/$', views.LoginView.as_view(), name="login"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout"),
    re_path(r'^userlist/$', views.UserInfoView.as_view(), name="userlist"),
    re_path(r'^createuser/$', views.UserCreateUserView.as_view(), name="createuser"),
    re_path(r'^changepasswd/$', views.UserChangePwd.as_view(), name="changepasswd"),

    re_path(r'^group/', include([
        re_path(r'^$', views.GroupListView.as_view(), name="grouplist"),
        re_path(r'^create/$', views.GroupCreateView.as_view(), name="groupcreate"),
        re_path(r'^delete/$', views.GroupDeleteView.as_view(), name="groupdelete"),
        re_path(r'^grouplist/$', views.GroupGrouplistView.as_view(), name="group_userlist"),
        re_path(r'permission/', include([
            re_path(r'^modify/$', views.ModifyGroupPermissionList.as_view(), name="group_permission_modify"),
            re_path(r'^view/$', views.PermissionViewView.as_view(), name='permission_view'),
        ])),
    ])),

    re_path(r'^permission/', include([
        re_path(r'^list/$', permission.PermissionListView.as_view(), name='permission_list'),
        re_path(r'^add/$', permission.PermissionCreateView.as_view(), name='permission_add'),
    ])),

]

cloud/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/9/3 0003 下午 3:03
__Author__ = '村长'

from django.urls import path, re_path
from cloud.tencent import views

app_name = 'cloud'

urlpatterns = [
        re_path('^tencent_list/$', views.TencentCmdbListView.as_view(), name="tencent_list"),
    ]






devops/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('', include("assets.urls")),
    path('resources/', include("resources.urls")),
    path('cloud/',include("cloud.urls")),

]

templates/users/group/group_user.html
{% extends 'base.html' %}


{% block title %} 用户组成员 {% endblock %}

{% block breadcrunb %}

    <h2>用户组成中</h2>

{% endblock %}


{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>组成员</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for group_user in group_user %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ group_user.username }}</td>
                <td>
                    <button class="btn btn-danger btn-sm" userid="{{ group_user.id }}" groupid= {{ g.id }}>删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}


{% block js %}

    <script>
        $(function () {
            //csrftoken
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    //xhr代指 XMLHttpRequest对象，
                    xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                }
            });

            // 删除组内用户
            $(".btn-danger").click(function () {
                var uid = $(this).attr("userid");
                var gid = $(this).attr("groupid");

                $.ajax({
                    url: "{% url 'accounts:group_userlist' %}",
                    dataType: "json",
                    type: "delete",
                    data: {'uid': uid, 'gid': gid},
                    success: function (res) {
                        if (res.status === 0) {
                            swal({
                                "title": "删除成功",
                                "text": "",
                                "type": "success"
                            }, function () {
                                setTimeout(function () {
                                    window.location.reload();
                                }, 200)
                            })
                        } else {
                            swal("删除失败", res.errmsg, "error");
                        }

                    }
                })

            })

        })
    </script>

{% endblock %}

templates/users/group/group_view_user_permissions.html
{% extends 'base.html' %}



{% block title %} 查看组权限 {% endblock %}

{% block breadcrunb %}

    <h2>查看组权限</h2>

{% endblock %}


{% block content %}

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>app名称</th>
            <th>model名称</th>
            <th>权限名称</th>
        </tr>
        </thead>
        <tbody>
        {% for grouppermission in group_permissions %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ grouppermission.content_type.app_label }}</td>
                <td>{{ grouppermission.content_type.model }}</td>
                <td>{{ grouppermission.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/users/group/grouplist.html
{% extends 'base.html' %}

{% block title %} 用户组信息 {% endblock %}

{% block breadcrunb %}

    <h2>用户组信息</h2>

{% endblock %}


{% block content %}
    <caption>
        {% if perms.auth.add_group %}
            <button class="btn btn-primary" id="add_group">创建用户组</button>
        {% endif %}
    </caption>

    <table class="table" style="margin-top: 10px">
        <thead>
        <tr>
            <th>#</th>
            <th>组名</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for group_obj in group %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ group_obj.name }}</td>
                <td>
                    <a type="button" class="btn btn-primary btn-sm"
                       href="{% url 'accounts:group_userlist' %}?gid={{ group_obj.id }}">成员列表</a>
                    <a href="{% url 'accounts:permission_view' %}?id={{ group_obj.id }}" type="button" class="btn btn-success btn-sm">查看权限</a>
                    {% if perms.auth.change_group %}
                        <a class="btn btn-info btn-sm"
                           href="{% url 'accounts:group_permission_modify' %}?gid={{ group_obj.id }}">修改权限</a>
                    {% endif %}
                    {% if perms.auth.delete_group %}
                        <button type="button" class="btn btn-danger btn-sm del_group deletedd"
                                groupid="{{ group_obj.id }}">删除
                        </button>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>



    <!-- 模态杠 -->

    <div class="modal fade" id="create_group" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4>添加group</h4>
                </div>
                <div class="modal-body form-inline">
                    <div class="form-group">
                        <label for="exampleInputName2">用户组：</label>
                        <input type="text" class="form-control" id="form_groupname" placeholder="请输入用户组名称"/>
                    </div>
                    <button class="btn btn-primary" id="create_group_btn">提交</button>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="取消">
                </div>

            </div>
        </div>
    </div>

{% endblock %}


{% block js %}

    <script>
        $(function () {
            //csrftoken
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    //xhr代指 XMLHttpRequest对象，
                    xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                }
            });

            // 添加用户组
            $("#add_group").click(function () {
                var create_group_modal = $("#create_group")
                create_group_modal.modal("show");

                // 点击提交按钮至数据后台
                $("#create_group_btn").click(function () {
                    var form_groupname_input = $("#form_groupname");
                    var group_name = form_groupname_input.val(); //获取值
                    form_groupname_input.val("");

                    if (group_name === "") {
                        swal("添加失败", "用户组名不能为空", "error");
                        return false;
                    }

                    $('#create_group').modal("hide");

                    $.ajax({
                        url: "{% url 'accounts:groupcreate' %}",
                        type: "post",
                        data: {"name": group_name},
                        success: function (ret) {
                            if (ret.status === 0) {
                                swal({
                                    "title": "用户组创建成功",
                                    "text": "",
                                    "type": "success"
                                }, function () {
                                    setTimeout(function () {
                                        window.location.reload();
                                    }, 200)
                                })
                            } else {
                                swal("用户组创建失败", ret.errmsg, "error")
                            }
                        }
                    })


                })
            });


            // 删除用户

            $(".del_group").click(function () {
                var gid = $(this).attr("groupid");
                $.ajax({
                    url: "{% url 'accounts:groupdelete' %}",
                    dataType: "json",
                    type: "delete",
                    data: {"gid": gid},
                    success: function (ret) {
                        if (ret.status === 0) {
                            swal({
                                "title": "用户组删除成功",
                                "text": "",
                                "type": "success"
                            }, function () {
                                setTimeout(function () {
                                    window.location.reload();
                                }, 200)
                            })
                        } else {
                            swal("用户组删除失败", ret.errmsg, "error")
                        }
                    }
                })
            });


        })
    </script>

{% endblock %}

templates/users/group/modify_group_permissions.html
{% extends "base.html" %}


{% block title %} 修改组权限{% endblock %}

{% block css %}
    <style>
        .check_label {
            user-select: none
        }
    .permission-point{
        margin-left: 230px !important;
    }
    .permission-context{
         width: 200px !important;
    }
    </style>

{% endblock %}

{% block content %}

    <form action="" class="form-horizontal" method="post">
    {% csrf_token %}
        <dl class="dl-horizontal">
            {% for contenttype in contenttypes %}
                <dt class="permission-context">{{ contenttype.app_label }} -> {{ contenttype.model }}</dt>
                <dd class="permission-point">
                    <ul class="list-unstyled">
                        {% for permission in contenttype.permission_set.all %}
                            <li>
                                <input type="checkbox" name="permission" value="{{ permission.id }}"
                                       {% if permission.id in group_permissions  %}
                                           checked
                                        {% endif %}
                                       id="{{ permission.codename }}_{{ forloop.counter }}">
                                <label class="check_label"
                                       for="{{ permission.codename }}_{{ forloop.counter }}">{{ permission.name }}</label>
                            </li>
                        {% endfor %}
                    </ul>

                </dd>
            {% endfor %}
        </dl>

    <div class="form-group form-footer">
        <div class="col-sm-offset-2 col-sm-6">
            <input type="hidden" name="groupid" value="{{ group }}">
            <button type="submit" class="btn btn-primary">提交</button>
            <button type="reset" class="btn btn-danger">重置</button>
        </div>

    </div>

    </form>


{% endblock %}