cloud/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/9/3 0003 下午 3:03
__Author__ = '村长'

from django.urls import path, re_path
from cloud.tencent import views

app_name = 'cloud'

urlpatterns = [
        re_path('^tencent_list/$', views.TencentCmdbListView.as_view(), name="tencent_list"),
    ]






devops/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('', include("assets.urls")),
    path('resources/', include("resources.urls")),
    path('cloud/',include("cloud.urls")),

]

resources/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/8/6 0006 下午 5:53
__Author__ = '村长'

from django.urls import path, re_path, include
from resources import views

app_name = 'resources'

urlpatterns = [
    re_path('^bussiness/', include([
        re_path(r'^list/$', views.RessourcessIndexView.as_view(), name="resource_list"),
        re_path(r'^add/$', views.RessourcessaddView.as_view(), name="resource_add"),
        re_path(r'^modify/$', views.RessourcessModifyView.as_view(), name="resource_modify"),
        re_path(r'^upload/$', views.RessourcessUploadView.as_view(), name="resource_upload"),
        # re_path(r'^upload/$', views.RessourcessUploadView, name="resource_upload"),
    ])),

]

resources/models.py
from django.db import models

class Bussiness(models.Model):
    """业务线"""

    business_type = (
        (0, "---请选择---"),
        (1, "O2M300"),
        (2, "O2M500"),
        (3, "O2M800"),
        (4, "IM800"),
        (5, "供应链")
    )

    business_chooics = models.IntegerField(choices=business_type)
    virIP = models.GenericIPAddressField(verbose_name="业务IP",db_index=True) #一台机器有多个业务,可以重复
    application = models.CharField(max_length=200, verbose_name="业务名称", db_index=True)
    port = models.IntegerField(verbose_name='应用端口', null=True, default="")
    component = models.CharField(verbose_name='组件用途', max_length=100)
    principal = models.CharField(verbose_name='开发负责人', max_length=32)
    ctime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    uptime = models.DateTimeField(verbose_name="更新时间", auto_now=True)
    note = models.CharField(verbose_name='备注', max_length=100, null=True)

    class Meta:
        db_table = "bussiness"


    def __str__(self):
        return self.virIP

templates/resources/resources.html
{% extends 'base.html' %}

{% block title %}业务环境{% endblock %}

{% block breadcrunb %}

    <h2>业务信息</h2>

{% endblock %}


{% block content %}

    <form class="form-inline"
          enctype="multipart/form-data">
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" id="exampleInputAmount" name="keyword"
                       placeholder="IP地址/应用名称" value="{% if keyword %}{{ keyword }} {% endif %}">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">搜索</button>

        {% if perms.product.add_bussiness %}
            <a class="btn  btn-success" href="{% url 'resources:resource_add' %}">添加业务</a>
        {% endif %}

        <a href="{% url 'resources:resource_upload' %}" class="btn btn-warning" type="button">导出excel</a>

{#        <button type="submit" name="Create" id="btn_import_paper" class="btn btn-danger "><i#}
{#                class="icon-upload-alt"></i>&nbsp;&nbsp;导入excel#}
{#        </button>#}
    </form>



    <table class="table table-striped table-bordered table-hover" style="margin-top: 10px; border: 5x">
        <thead>
        <tr>
            <th>#</th>
            <th>业务IP</th>
            <th>业务名称</th>
            <th>业务端口</th>
            <th>业务用途</th>
            <th>业务线</th>
            <th>上线时间</th>
            <th>更新时间</th>
            <th>负责人</th>
            <th>备注</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ obj.virIP }}</td>
                <td>{{ obj.application }}</td>
                <td>{{ obj.port }}</td>
                <td>{{ obj.component }}</td>
                <td>{{ obj.get_business_chooics_display }}</td>
                <td>{{ obj.ctime|date:"Y-m-d H:i" }}</td>
                <td>{{ obj.uptime|date:"Y-m-d H:i" }}</td>
                <td>{{ obj.principal }}</td>
                <td>{{ obj.note }}</td>
                <td>
                    <div class="btn-group">
                        {% if perms.resources.change_bussiness %}
                        <a href="{% url 'resources:resource_modify' %}?id={{ obj.id }}"
                           class="btn btn-primary btn-sm ye-update">修改</a>
                        {% endif %}
                        <button class="btn btn-danger btn-sm ye-del deleteBusiness" data-id="{{ obj.id }}">删除</button>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <div class="row">
        <div class="col-sm-6">
            <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
                显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index }}] 至 [{{ page_obj.end_index }}] 的数据
            </div>
        </div>
        {% include "paginator.html" %}
    </div>

{% endblock %}


{% block js %}
    <script>

        $(function () {
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    //xhr代指 XMLHttpRequest对象，
                    xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                }
            });

            // 删除业务线

            $(".deleteBusiness").click(function () {
                var delete_bussiness = $(this).attr('data-id');

                $.ajax({
                    url: "{% url 'resources:resource_list' %}",
                    type: 'delete',
                    data: {'bid': delete_bussiness},
                    success: function (res) {
                        if (res.status === 0) {
                            swal({
                                "title": "业务删除成功",
                                "text": "",
                                "type": "success"
                            }, function () {
                                setTimeout(function () {
                                    location.reload();
                                })
                            })
                        } else {
                            swal("操作失败", res.errmsg, "error");
                        }
                    }
                });
            });
        });
    </script>

{% endblock %}

templates/resources/resources_add.html
{% extends 'base.html' %}

{% block title %}添加业务{% endblock %}


{% block breadcrunb %}

    <h2>添加业务</h2>

{% endblock %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-1">
                <form action="{% url 'resources:resource_add' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group {% if obj.virIP.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.virIP.label }}
                        {{ obj.virIP }}
                        <span class="help-block">{{ obj.virIP.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.application.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.application.label }}
                        {{ obj.application }}
                        <span class="help-block">{{ obj.application.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.port.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.port.label }}
                        {{ obj.port }}
                        <span class="help-block">{{ obj.port.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.component.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.component.label }}
                        {{ obj.component }}
                        <span class="help-block">{{ obj.component.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.business_chooics.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.business_chooics.label }}
                        {{ obj.business_chooics }}
                        <span class="help-block">{{ obj.business_chooics.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.principal.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.principal.label }}
                        {{ obj.principal }}
                        <span class="help-block">{{ obj.principal.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.note.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.note.label }}
                        {{ obj.note }}
                        <span class="help-block">{{ obj.note.errors.0 }}</span>
                    </div>


                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">提交</button>
                        <button type="reset" class="btn btn-danger">重置</button>
                    </div>

                </form>
            </div>
        </div>

    </div>

{% endblock %}

templates/resources/resources_update.html
{% extends 'base.html' %}

{% block title %}更新业务{% endblock %}


{% block breadcrunb %}

    <h2>更新业务</h2>

{% endblock %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-1">
                <form  method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group {% if obj.virIP.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.virIP.label }}
                        {{ obj.virIP }}
                        <span class="help-block">{{ obj.virIP.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.application.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.application.label }}
                        {{ obj.application }}
                        <span class="help-block">{{ obj.application.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.port.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.port.label }}
                        {{ obj.port }}
                        <span class="help-block">{{ obj.port.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.component.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.component.label }}
                        {{ obj.component }}
                        <span class="help-block">{{ obj.component.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.business_chooics.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.business_chooics.label }}
                        {{ obj.business_chooics }}
                        <span class="help-block">{{ obj.business_chooics.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.principal.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.principal.label }}
                        {{ obj.principal }}
                        <span class="help-block">{{ obj.principal.errors.0 }}</span>
                    </div>

                    <div class="form-group {% if obj.note.errors.0 %}has-error{% else %}has-success{% endif %}">
                        {{ obj.note.label }}
                        {{ obj.note }}
                        <span class="help-block">{{ obj.note.errors.0 }}</span>
                    </div>


                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">提交</button>
                        <button type="reset" class="btn btn-danger">重置</button>
                    </div>

                </form>
            </div>
        </div>

    </div>

{% endblock %}