accounts/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/8/5 0005 上午 10:14
__Author__ = '村长'
from django.urls import path, re_path, include
from accounts import views
from accounts import permission

app_name = 'accounts'

urlpatterns = [

    re_path(r'^login/$', views.LoginView.as_view(), name="login"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout"),
    re_path(r'^userlist/$', views.UserInfoView.as_view(), name="userlist"),
    re_path(r'^createuser/$', views.UserCreateUserView.as_view(), name="createuser"),
    re_path(r'^changepasswd/$', views.UserChangePwd.as_view(), name="changepasswd"),

    re_path(r'^group/', include([
        re_path(r'^$', views.GroupListView.as_view(), name="grouplist"),
        re_path(r'^create/$', views.GroupCreateView.as_view(), name="groupcreate"),
        re_path(r'^delete/$', views.GroupDeleteView.as_view(), name="groupdelete"),
        re_path(r'^grouplist/$', views.GroupGrouplistView.as_view(), name="group_userlist"),
        re_path(r'permission/', include([
            re_path(r'^modify/$', views.ModifyGroupPermissionList.as_view(), name="group_permission_modify"),
            re_path(r'^view/$', views.PermissionViewView.as_view(), name='permission_view'),
        ])),
    ])),

    re_path(r'^permission/', include([
        re_path(r'^list/$', permission.PermissionListView.as_view(), name='permission_list'),
        re_path(r'^add/$', permission.PermissionCreateView.as_view(), name='permission_add'),
    ])),

]

cloud/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/9/3 0003 下午 3:03
__Author__ = '村长'

from django.urls import path, re_path
from cloud.tencent import views

app_name = 'cloud'

urlpatterns = [
        re_path('^tencent_list/$', views.TencentCmdbListView.as_view(), name="tencent_list"),
    ]






devops/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('', include("assets.urls")),
    path('resources/', include("resources.urls")),
    path('cloud/',include("cloud.urls")),

]

resources/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/8/6 0006 下午 5:53
__Author__ = '村长'

from django.urls import path, re_path, include
from resources import views

app_name = 'resources'

urlpatterns = [
    re_path('^bussiness/', include([
        re_path(r'^list/$', views.RessourcessIndexView.as_view(), name="resource_list"),
        re_path(r'^add/$', views.RessourcessaddView.as_view(), name="resource_add"),
        re_path(r'^modify/$', views.RessourcessModifyView.as_view(), name="resource_modify"),
        re_path(r'^upload/$', views.RessourcessUploadView.as_view(), name="resource_upload"),
        # re_path(r'^upload/$', views.RessourcessUploadView, name="resource_upload"),
    ])),

]

templates/base.html
<!DOCTYPE html>
<html>

<!-- head骨架部分 -->
<head>

    {% load static %}

    <!-- 母版定义好最基础的资源，保证骨架没问题，各个子页面可以根据需要在block中重写 -->

    <meta charset="utf-8">
    <title>{% block title %} 自动化运维平台 {% endblock %} </title>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- 字体库 -->
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
    <!-- 图标库 -->
    <link rel="stylesheet" href="{% static 'plugins/Ionicons/css/ionicons.min.css' %}">
    <!-- 弹框库 -->
    <link rel="stylesheet" href="{% static 'plugins/alert/sweet-alert.css' %}">
    <!-- 表格库 -->
    <link rel="stylesheet" href="{% static 'plugins/footable/footable.core.css' %}">
    <!-- 选框库 -->
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <!-- 时间库 -->
    <link rel="stylesheet" href="{% static 'plugins/timepicker/bootstrap-datepicker.min.css' %}">

    <!-- AdminLTE模版样式-->
    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="/static/css/_all-skins.min.css">

    <!-- DataTble样式 -->
    <link rel="stylesheet" href="/static/css/datatable.css">
    <link rel="stylesheet" href="/static/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="/static/css/dataTables.bootstrap.min.css">


    <!-- 子页面可以自定义引入css -->
    {% block css %}
    {% endblock %}

</head>

<!-- body骨架部分 -->
<body class="hold-transition skin-blue sidebar-mini">

<!--整体骨架样式-->
<div class="wrapper">

    <!--第一层头部骨架-->
    <header class="main-header">

        <!-- 第一层左上角logo部分 -->
        <a href="#" class="logo">
            <!-- 收缩时显示DO -->
            <span class="logo-mini"><b>D</b>O</span>
            <!-- 伸展时显示DevOps -->
            <span class="logo-lg"><b>DevOps</b></span>
        </a>

        <!-- 第一层右边内容 -->
        <nav class="navbar navbar-static-top">

            <!-- 控制收缩和伸展的按钮-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"></a>

            <!-- 左边菜单栏 -->
            <div class="navbar-custom-menu">
                <!-- 用户退出及个人信息部分 -->
                <ul class="nav navbar-nav">

                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
                            <span class="hidden-xs">
              {% if request.user.is_authenticated %} {{ request.user.username }} {% else %} 游客 {% endif %}
          </span>
                        </a>

                        <ul class="dropdown-menu">
                            <!-- 用户图像 -->
                            <li class="user-header">
                                <img src="{% static '/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                                <p>
                                    {{ request.user.username }}
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{#% url 'users:user_detail' request.user.id %#}"
                                       class="btn btn-default btn-flat">个人主页</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'accounts:logout' %}" class="btn btn-default btn-flat">退出</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>

        </nav>
    </header>

    <!-- 第二层左边 -->
    <aside class="main-sidebar">

        <!-- 第二层左边骨架 -->
        <section class="sidebar">

            <!-- 用户介绍 -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static 'img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p></p>
                    <a href="#"><i class="fa fa-circle text-success"></i>欢迎您:{{ request.user.username }}</a>
                </div>
            </div>


            <!-- 菜单栏 -->
            <ul class="sidebar-menu" data-widget="tree">
                <!-- 菜单栏 -->
                <li class="header">让技术产生生产力</li>

                <!-- Dashboard -->
                <li>
                    <a href="/">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>

                <!-- 用户权限管理 -->
                {% if perms.auth.view_user %}
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-users"></i>
                            <span>用户权限管理</span>
                            <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                        </a>
                        <ul class="treeview-menu">

                            <li><a href="{% url 'accounts:userlist' %}"><i class="fa fa-circle-o"></i> 用户管理</a></li>
                            <li><a href="{% url 'accounts:grouplist' %}"><i class="fa fa-circle-o"></i> 用户组管理</a></li>
                            <li><a href="{#% url 'users:role_list' %#}"><i class="fa fa-circle-o"></i> 角色管理</a></li>
                            <li><a href="{% url 'accounts:permission_list' %}"><i class="fa fa-circle-o"></i> 权限管理</a>
                            </li>
                            {#                        {% else %}#}
                            {#                            <li><a href="{#% url 'users:user_detail' request.user.id %#}"><i
                                class="fa fa-circle-o"></i>个人中心</a>#}
                            {#                            </li>#}
                            {#                            <li><a href="{#% url 'users:user_detail' request.user.id %#}"><i
                                class="fa fa-circle-o"></i>用户列表</a>#}

                        </ul>
                    </li>
                {% endif %}

                <!-- CMDB系统 -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-database"></i>
                        <span>业务系统</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'resources:resource_list' %}"><i class="fa fa-circle-o"></i> 业务线管理</a></li>
                        {#                        <li><a href="{#% url 'cmdb:product_detail' 1 %#}"><i
                            class="fa fa-circle-o"></i> 产品线管理</a></li>#}
                    </ul>
                </li>

                <!-- 多云CMDB -->

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-database"></i>
                        <span>多云CMDB</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'cloud:tencent_list' %}"><i class="fa fa-circle-o"></i> 腾讯云</a></li>
                        <li><a href="{#  #}% url 'cmdb:product_detail' 1 %"><i class="fa fa-circle-o"></i> 阿里云</a></li>
                    </ul>
                </li>

                <!-- 代码发布系统 -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-rocket"></i>
                        <span>代码发布系统</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{#% url 'deploy:project_list' %#}"><i class="fa fa-circle-o"></i>项目列表</a></li>
                        <li><a href="{#% url 'deploy:apply' %#}"><i class="fa fa-circle-o"></i> 申请上线</a></li>
                        <li><a href="{#% url 'deploy:list' %#}"><i class="fa fa-circle-o"></i> 申请列表 </a></li>
                        <li><a href="{#% url 'deploy:history' %#}"><i class="fa fa-circle-o"></i> 发布历史</a></li>
                    </ul>
                </li>

                <!-- 工单系统 -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-tasks"></i>
                        <span>工单系统</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{#% url 'workorder:apply' %#}"><i class="fa fa-circle-o"></i> 工单申请</a></li>
                        <li><a href="{#% url 'workorder:list' %#}"><i class="fa fa-circle-o"></i> 工单列表</a></li>
                        <li><a href="{#% url 'workorder:history' %#}"><i class="fa fa-circle-o"></i> 工单历史</a></li>
                    </ul>
                </li>

                <!-- 图书管理系统 -->


            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- 第二层右边内容部分 -->
    <div class="content-wrapper">

        <!-- 面包屑导航部分 -->
        <section class="content-header">
            {% block breadcrunb %}
            {% endblock %}
        </section>

        <!-- 主要内容 -->
        <section class="content">
            {% block content %}
            {% endblock %}
        </section>

    </div>
    <!-- 第二层右边结束 -->


    <!--第三层底部-->
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b></b>
        </div>
        <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">adminlte</a></strong> All rights reserved
    </footer>

    <!-- ./wrapper结束-->
</div>


</body>


<!-- 公共js部分 -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.cookie.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- alert -->
<script src="{% static 'plugins/alert/sweet-alert.min.js' %}"></script>
<!-- footable -->
<script src='{% static 'plugins/footable/footable.all.min.js' %}'></script>
<!-- datepicker -->
<script src="{% static 'plugins/timepicker/bootstrap-datepicker.js' %}"></script>
<!-- select2 -->
<script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
<!-- ace -->
<script src="{% static 'plugins/ace/ace.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'plugins/ace/ext-language_tools.js' %}" type="text/javascript" charset="utf-8"></script>
<!-- ace -->
<script src="{% static 'plugins/ladda/spin.min.js' %}"></script>
<script src="{% static 'plugins/ladda/ladda.min.js' %}"></script>
<script src="{% static 'plugins/ladda/ladda.jquery.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>
<script src="{% static 'js/dashboard2.js' %}"></script>
<script src="{% static 'js/demo.js' %}"></script>


<!--DataTable-->
{#<script src="{% static 'js/datatable.js' %}"></script>#}
<script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>



<!-- 子页面可以根据需要添加js -->
{% block js %}
{% endblock %}

</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>权限提示</title>
    <style>
    </style>
</head>
<center>
<body style="background-color: #ecf0f5; color: red" >
        <h1><p class="text-center">操作失败</p></h1>
        <h3><p class="text-center">没有权限</p></h3>
</body>
    </center>
</html>

templates/index.html
{% extends "base.html" %}

<!-- 重写母版的title -->
{% block title %}首页{% endblock %}

<!-- 重写母版的breadcrunb -->
{% block breadcrunb %}
  <h1>Dashboard</h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i>Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
{% endblock %}


<!-- 填充母版的内容 -->
{% block content %}

<!-- 第一层仪表图-->
<div class="row">

<!-- 第一层第一个图标-->
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>

    <div class="info-box-content">
      <span class="info-box-text">CPU Traffic</span>
      <span class="info-box-number">90<small>%</small></span>
    </div>
    <!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->

<!-- 第一层第二个图标-->
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-red"><i class="fa fa-google-plus"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Likes</span>
      <span class="info-box-number">41,410</span>
    </div>
    <!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->

<!-- 第一层第三个图标-->
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>

    <div class="info-box-content">
      <span class="info-box-text">Sales</span>
      <span class="info-box-number">760</span>
    </div>
    <!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->

<!-- 第一层第四个图标-->
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

    <div class="info-box-content">
      <span class="info-box-text">New Members</span>
      <span class="info-box-number">2,000</span>
    </div>
    <!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->

</div>
<!--第一层结束 -->

<!-- 第二层内容-->
<div class="row">
<div class="col-md-12">
  <div class="box">
    <!-- 内容头部 -->
    <div class="box-header with-border">
      <h3 class="box-title">Monthly Recap Report</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <div class="btn-group">
          <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-wrench"></i></button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </div>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /头部结束-->

    <!-- 正式内容部分 -->
    <div class="box-body">
      <div class="row">
        <!-- 左边部分内容 -->
        <div class="col-md-8">
          <p class="text-center">
            <strong>Sales: 1 Jan, 2014 - 30 Jul, 2014</strong>
          </p>
          <div class="chart">
            <!-- Sales Chart Canvas -->
            <canvas id="salesChart" style="height: 180px;"></canvas>
          </div>
          <!-- /.chart-responsive -->
        </div>
        <!-- /.col -->

        <!-- 右边部分内容 -->
        <div class="col-md-4">
          <p class="text-center">
            <strong>Goal Completion</strong>
          </p>
          <div class="progress-group">
            <span class="progress-text">Add Products to Cart</span>
            <span class="progress-number"><b>160</b>/200</span>

            <div class="progress sm">
              <div class="progress-bar progress-bar-aqua" style="width: 80%"></div>
            </div>
          </div>
          <!-- /.progress-group -->
          <div class="progress-group">
            <span class="progress-text">Complete Purchase</span>
            <span class="progress-number"><b>310</b>/400</span>
            <div class="progress sm">
              <div class="progress-bar progress-bar-red" style="width: 80%"></div>
            </div>
          </div>
          <!-- /.progress-group -->
          <div class="progress-group">
            <span class="progress-text">Visit Premium Page</span>
            <span class="progress-number"><b>480</b>/800</span>
            <div class="progress sm">
              <div class="progress-bar progress-bar-green" style="width: 80%"></div>
            </div>
          </div>
          <!-- /.progress-group -->
          <div class="progress-group">
            <span class="progress-text">Send Inquiries</span>
            <span class="progress-number"><b>250</b>/500</span>
            <div class="progress sm">
              <div class="progress-bar progress-bar-yellow" style="width: 80%"></div>
            </div>
          </div>
          <!-- /.progress-group -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>

  </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /第二层结束 -->

<!-- 第三层内容-->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

  <!-- TABLE: LATEST ORDERS -->
  <div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title">Latest Orders</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="table-responsive">
        <table class="table no-margin">
          <thead>
          <tr>
            <th>Order ID</th>
            <th>Item</th>
            <th>Status</th>
            <th>Popularity</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><a href="pages/examples/invoice.html">OR9842</a></td>
            <td>Call of Duty IV</td>
            <td><span class="label label-success">Shipped</span></td>
            <td>
              <div class="sparkbar" data-color="#00a65a" data-height="20">90,80,90,-70,61,-83,63</div>
            </td>
          </tr>
          <tr>
            <td><a href="pages/examples/invoice.html">OR1848</a></td>
            <td>Samsung Smart TV</td>
            <td><span class="label label-warning">Pending</span></td>
            <td>
              <div class="sparkbar" data-color="#f39c12" data-height="20">90,80,-90,70,61,-83,68</div>
            </td>
          </tr>
          <tr>
            <td><a href="pages/examples/invoice.html">OR7429</a></td>
            <td>iPhone 6 Plus</td>
            <td><span class="label label-danger">Delivered</span></td>
            <td>
              <div class="sparkbar" data-color="#f56954" data-height="20">90,-80,90,70,-61,83,63</div>
            </td>
          </tr>
          <tr>
            <td><a href="pages/examples/invoice.html">OR7429</a></td>
            <td>Samsung Smart TV</td>
            <td><span class="label label-info">Processing</span></td>
            <td>
              <div class="sparkbar" data-color="#00c0ef" data-height="20">90,80,-90,70,-61,83,63</div>
            </td>
          </tr>
          <tr>
            <td><a href="pages/examples/invoice.html">OR1848</a></td>
            <td>Samsung Smart TV</td>
            <td><span class="label label-warning">Pending</span></td>
            <td>
              <div class="sparkbar" data-color="#f39c12" data-height="20">90,80,-90,70,61,-83,68</div>
            </td>
          </tr>
          <tr>
            <td><a href="pages/examples/invoice.html">OR7429</a></td>
            <td>iPhone 6 Plus</td>
            <td><span class="label label-danger">Delivered</span></td>
            <td>
              <div class="sparkbar" data-color="#f56954" data-height="20">90,-80,90,70,-61,83,63</div>
            </td>
          </tr>
          <tr>
            <td><a href="pages/examples/invoice.html">OR9842</a></td>
            <td>Call of Duty IV</td>
            <td><span class="label label-success">Shipped</span></td>
            <td>
              <div class="sparkbar" data-color="#00a65a" data-height="20">90,80,90,-70,61,-83,63</div>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.box-body -->

  </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /第三层结束-->
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <title>DevOps | Log in</title>
    <!-- Bootstrap 3.3.7 -->
    <style>
{#        #image{#}
{#            background-image: url("/static/img/login.png");#}
{#        }#}
    </style>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/static/plugins/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/css/AdminLTE.min.css">


</head>

<body class="hold-transition login-page" id="image">
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>DevOps</b></a>
    </div>
    <!-- /.login-logo -->

    <div class="login-box-body">
        <p class="login-box-msg">让技术产生价值</p>

        <!--登陆表单-->
        <form id="from_login" action="{% url 'accounts:login' %}" method="post" onsubmit="return false">
            {% csrf_token %}
            <!--用户名-->
            <div class="form-group has-feedback">
                <input id ="user" name="username" type="text" class="form-control" placeholder="用户名">
                {#                {% if forms.username.errors %}#}
                {#                    <span style="color:red">{{ forms.username.errors }}</span>#}
                {#                {% endif %}#}
            </div>
            <!--密码-->
            <div class="form-group has-feedback">
                <input name="password" type="password" class="form-control" placeholder="密码">
                {#                {% if forms.password.errors %}#}
                {#                    <span style="color:red">{{ forms.password.errors }}</span>#}
                {#                {% endif %}#}
                {#                 <span id="errors" style="color:red"></span>#}
            </div>
            <!--错误信息及登陆-->
            <div class="row">
                <div class="col-xs-8">
                    {#                    <span id="errors" style="color:red">{% if msg %} {{ msg }} {% else %}  {% endif %}</span>#}
                    <span id="errors" style="color:red"></span>
                </div>
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
                </div>
            </div>
        </form>

        <!--忘记密码连接-->
{#        <a id="forget" >忘记密码</a><br>#}
        <a id='forget' style="cursor:pointer">忘记密码</a>
    </div>

</div>  <!--login-box-->
</body>
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/jquery.cookie.js"></script>
<script src="/static/js/sweetalert.min.js"></script>

<script>

    // 忘记密码
    $('#forget').click(function () {
        str="请联系管理员帮您重置密码"+'\n'+"邮箱：xxxxxx@gome.com.cn";
        swal(str)
    });

    $('button').click(function () {
        $.ajax({
            url: "{% url 'accounts:login' %}",
            type: "post",
            dataType: "json",
            data: $('#from_login').serialize(),
            headers: {'X-CSRFtoken': $.cookie('csrftoken')},
            success: function (data) {
                console.log(data);
                if (data.status === 0) {
                    location.href = data["next_url"]
                } else {
                    $('#errors').html(data['errmsg']);
                    console.log(data["errmsg"])
                }
            }
        });
    });
</script>


</html>

templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>权限提示</title>
    <style>
    </style>
</head>
<center>
<body style="background-color: #ecf0f5; color: seagreen" >
        <h1><p class="text-center">操作成功</p></h1>

</body>
    </center>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>xxtext</h1>
</body>
</html>