accounts/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/8/5 0005 上午 10:14
__Author__ = '村长'
from django.urls import path, re_path, include
from accounts import views
from accounts import permission

app_name = 'accounts'

urlpatterns = [

    re_path(r'^login/$', views.LoginView.as_view(), name="login"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout"),
    re_path(r'^userlist/$', views.UserInfoView.as_view(), name="userlist"),
    re_path(r'^createuser/$', views.UserCreateUserView.as_view(), name="createuser"),
    re_path(r'^changepasswd/$', views.UserChangePwd.as_view(), name="changepasswd"),

    re_path(r'^group/', include([
        re_path(r'^$', views.GroupListView.as_view(), name="grouplist"),
        re_path(r'^create/$', views.GroupCreateView.as_view(), name="groupcreate"),
        re_path(r'^delete/$', views.GroupDeleteView.as_view(), name="groupdelete"),
        re_path(r'^grouplist/$', views.GroupGrouplistView.as_view(), name="group_userlist"),
        re_path(r'permission/', include([
            re_path(r'^modify/$', views.ModifyGroupPermissionList.as_view(), name="group_permission_modify"),
            re_path(r'^view/$', views.PermissionViewView.as_view(), name='permission_view'),
        ])),
    ])),

    re_path(r'^permission/', include([
        re_path(r'^list/$', permission.PermissionListView.as_view(), name='permission_list'),
        re_path(r'^add/$', permission.PermissionCreateView.as_view(), name='permission_add'),
    ])),

]

cloud/urls.py
#! /usr/bin/env python
# encoding: utf-8
# @Time :2019/9/3 0003 下午 3:03
__Author__ = '村长'

from django.urls import path, re_path
from cloud.tencent import views

app_name = 'cloud'

urlpatterns = [
        re_path('^tencent_list/$', views.TencentCmdbListView.as_view(), name="tencent_list"),
    ]






devops/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('', include("assets.urls")),
    path('resources/', include("resources.urls")),
    path('cloud/',include("cloud.urls")),

]

templates/users/changepassword.html
{% extends "base.html" %}

{% block title %}密码修改{% endblock %}

{% block breadcrunb %}
    <h1>
        用户修改密码
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">修改密码</li>
    </ol>
{% endblock %}



{% block content %}

    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">

                <div class="box-header with-border">
                    <h3 class="box-title">修改密码</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.box-header -->


                <div class="box-body">
                    {% if msg %}
                        <div class="alert alert-danger">{{ msg }}</div>
                    {% endif %}
                    <form class="form-horizontal" action="{% url 'accounts:changepasswd' %}?id={{ u.id }}" method="post" novalidate>
                        {% csrf_token %}
{#                        <input type="hidden" name="uid" value="{{ u.id }}">#}

                        <div class="form-group {% if form.password.errors.0 %}has-error{% else %}has-success{% endif %}">
                            <label class="col-sm-2 control-label">新密码：</label>

                            <div class="col-sm-6">
                                {{ form.password }}
                                <span class="help-block">{{ form.password.errors.0 }}</span>

                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">确认密码：</label>
                            <div class="col-sm-6 {% if form.re_password.errors.0 %}has-error{% else %}has-success{% endif %}">
                              {{ form.re_password }}
                                 <span class="help-block">{{ form.re_password.errors.0 }}</span>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <input type="hidden" name="uid" value="{{ u.id }}">
                                <button class="btn btn-white" type="reset">取消</button>
                                <button type="submit" class="btn btn-primary ">确定</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

templates/users/createuser.html
{% extends "base.html" %}


{% block title %} 添加用户 {% endblock %}


{% block breadcrunb %}

<h2>创建用户</h2>

{% endblock %}

{% block content %}

     <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-1">

                <form action="{% url 'accounts:createuser' %}" method="post" novalidate id="fromuser">
                        {% csrf_token %}
                        <div class="form-group {% if obj.username.errors.0 %}has-error{% else %}has-success{% endif %}">
                            {{ obj.username.label }}
                            {{ obj.username }}
                            <span class="help-block">{{ obj.username.errors.0 }}</span>
                        </div>

                        <div class="form-group {% if obj.password.errors.0 %}has-error{% else %}has-success{% endif %}">
                            {{ obj.password.label }}
                            {{ obj.password }}
                        </div>

                        <div class="form-group {% if obj.re_password.errors.0 %}has-error{% else %}has-success{% endif %}">
                            {{ obj.re_password.label }}
                            {{ obj.re_password }}
                        </div>
                        <span class="help-block">{{ obj.re_password.errors.0 }}</span>
                        <div class="form-group {% if obj.email.errors.0 %}has-error{% else %}has-success{% endif %}">
                            {{ obj.email.label }}
                            {{ obj.email }}
                        </div>
                        <span class="help-block">{{ obj.email.errors.0 }}</span>

                        <div class="modal-footer">
                            <button type="reset" class="btn btn-danger" data-dismiss="modal">重置</button>
                            <button type="submit" class="btn btn-primary" id="sure">确认</button>
                        </div>
                    </form>


            </div>
        </div>
     </div>


{% endblock %}

templates/users/users.html
{% extends 'base.html' %}

{% block title %}用户信息{% endblock %}

{% block breadcrunb %}
    <h2>用户信息</h2>
{% endblock %}

{% block content %}
    <caption>
        <form class="form-inline">
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" id="exampleInputAmount" name="keyword"
                           placeholder="查询用户" value="{% if keyword %}{{ keyword }} {% endif %}">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">搜索</button>
            {% if perms.auth.add_user %}
                <a href="{% url 'accounts:createuser' %}" type="button" class="btn btn-success" id="add_user">创建用户</a>
            {% endif %}
        </form>
    </caption>


    <table class="table table-striped table-bordered table-hover success" style="margin-top: 10px">
        <thead>
        <tr>
            <th>#</th>
            <th>用户名</th>
            <th>电子邮件</th>
            <th>状态</th>
            <th>最后登录时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>

        {% for us in username %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ us.username }}</td>
                <td>{{ us.email }}</td>
                {% if us.is_active == True %}
                    <td>激活</td>
                {% else %}
                    <td>禁用</td>
                {% endif %}
                <td>{{ us.last_login | date:"Y-m-d H:i" }}</td>
                <td>
                {% if perms.auth.change_user %}
                    <div class="btn-group">
                        <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu1"
                                data-toggle="dropdown">
                            修改
                            <span class="caret"></span>
                        </button>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

                             <li role="presentation">
                                <a href="{% url 'accounts:changepasswd' %}?id={{ us.id }}" class="changepassword" data="{{ us.id }}" role="menuitem" tabindex="-1"
                                     >修改密码</a>
                            </li>

                            <li role="presentation">
                                <a role="menuitem" tabindex="-1"
                                   data={{ us.id }}  class="user_to_group">添加到指定组</a>
                            </li>

                        </ul>
                    {% endif %}

                        {% if us.is_active %}
                            <button type="button" class="btn btn-sm btn-warning modify_user_status"
                                    status="{{ us.is_active|lower }}" data="{{ us.id }}">禁用
                            </button>
                        {% else %}

                            <button type="button" class="btn btn-sm btn-info modify_user_status "
                                    status="{{ us.is_active|lower }}" data="{{ us.id }}">启用
                            </button>
                        {% endif %}

                        <button type="button" class="btn btn-sm btn-danger delete_user" data="{{ us.id }}">
                            删除
                        </button>

                    </div>
                </td>
            </tr>

        {% endfor %}

        </tbody>
    </table>


    <!-- 分页 -->
    <div class="row">
        <div class="col-sm-6">
            <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
                显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index }}] 至 [{{ page_obj.end_index }}] 的数据
            </div>
        </div>
        {% include "paginator.html" %}
    </div>


    <!-- 模态框 -->

    <div class="modal fade" id="user_to_group_modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>

                    <h4 id="user_to_group_modal_title">将用户添加至组</h4>

                </div>
                <div class="modal-body clearfix">
                    <div class="col-xs-8" id="select_service_id">
                        <select class="chosen-select chosen-transparent form-control" id="all_user_group">
                            {% for i in group_dd %}
                                <option value="{{ i.id }}">{{ i.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary" id="user_to_group_btn">提交</button>
                </div>
                <div class="modal-footer">

                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="取消">
                </div>

            </div>
        </div>
    </div>




{% endblock %}


{% block js %}

    <script>
        $(function () {
            //csrftoken
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    //xhr代指 XMLHttpRequest对象，
                    xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                }
            });

            // 删除用户

            $(".delete_user").click(function () {
                var uid = $(this).attr("data");
                $.ajax({
                    url: "{% url 'accounts:userlist' %}",
                    type: "delete",
                    data: {uid: uid},
                    success: function (res) {
                        if (res.status === 0) {
                            swal({
                                "title": "用户删除成功",
                                "text": res.errmsg,
                                "type": "success"
                            }, function () {
                                setTimeout(function () {
                                    window.location.reload()
                                }, 200)
                            })
                        } else {
                            swal("用户删除失败", res.errmsg, "error")
                        }
                    }
                })
            });


            // 用户开启与禁止
            $(".modify_user_status").click(function () {
                var uid = $(this).attr("data");
                $.ajax({
                    url: "",
                    type: "put",
                    data: {'uid': uid},
                    success: function (res) {
                        if (res.status === 0) {
                            location.reload()
                        } else {
                            swal("操作失败", res.errmsg, "error");
                        }
                    }
                })
            });


            // 将用户添加至指定组
            $(".user_to_group").click(function () {
                var uid = $(this).attr("data");
                $("#user_to_group_modal").modal("show");

                $("#user_to_group_btn").click(function () {
                    var groupid = $(".chosen-select").val();
                    $.ajax({
                        url: "{% url 'accounts:userlist' %}",
                        dataType: "json",
                        type: "post",
                        data: {"uid": uid, "gid": groupid},
                        success: function (data) {
                            if (data.status === 0) {
                                swal({
                                    "title": "用户组添加成功",
                                    "text": "",
                                    "type": "success"
                                }, function () {
                                    setTimeout(function () {
                                        window.location.reload()
                                    }, 200)
                                })
                            } else {
                                swal('操作失败', data.errmsg, 'error');
                                $('#user_to_group_modal').modal('hide');

                            }
                        }
                    })
                })


            });




        });
    </script>


{% endblock %}